keyconfig_version = (3, 4, 6)
keyconfig_data = \
[("Curve",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'TOPBAR_MT_edit_curve_add'),
       ],
      },
     ),
    ("curve.handle_type_set", {"type": 'V', "value": 'PRESS'}, None),
    ("curve.vertex_add", {"type": 'RIGHTMOUSE', "value": 'CLICK', "oskey": True}, None),
    ("curve.vertex_add", {"type": 'RIGHTMOUSE', "value": 'CLICK', "ctrl": True}, None),
    ("curve.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("curve.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("curve.select_all",
     {"type": 'I', "value": 'PRESS', "oskey": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("curve.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("curve.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("curve.select_row", {"type": 'R', "value": 'PRESS', "shift": True}, None),
    ("curve.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "oskey": True, "repeat": True}, None),
    ("curve.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("curve.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "oskey": True, "repeat": True}, None),
    ("curve.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("curve.select_linked", {"type": 'L', "value": 'PRESS', "oskey": True}, None),
    ("curve.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("curve.select_similar", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("curve.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("curve.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("curve.shortest_path_pick", {"type": 'LEFTMOUSE', "value": 'CLICK', "oskey": True}, None),
    ("curve.shortest_path_pick", {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True}, None),
    ("curve.separate", {"type": 'P', "value": 'PRESS'}, None),
    ("curve.split", {"type": 'Y', "value": 'PRESS'}, None),
    ("curve.extrude_move", {"type": 'E', "value": 'PRESS'}, None),
    ("curve.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("curve.make_segment", {"type": 'F', "value": 'PRESS'}, None),
    ("curve.cyclic_toggle", {"type": 'C', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_curve_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_curve_delete'),
       ],
      },
     ),
    ("curve.dissolve_verts", {"type": 'X', "value": 'PRESS', "oskey": True}, None),
    ("curve.dissolve_verts", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("curve.dissolve_verts", {"type": 'DEL', "value": 'PRESS', "oskey": True}, None),
    ("curve.dissolve_verts", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("curve.tilt_clear", {"type": 'T', "value": 'PRESS', "alt": True}, None),
    ("transform.tilt", {"type": 'T', "value": 'PRESS', "oskey": True}, None),
    ("transform.tilt", {"type": 'T', "value": 'PRESS', "ctrl": True}, None),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'CURVE_SHRINKFATTEN'),
       ],
      },
     ),
    ("curve.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("curve.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("curve.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("curve.normals_make_consistent", {"type": 'N', "value": 'PRESS', "shift": True}, None),
    ("object.vertex_parent_set", {"type": 'P', "value": 'PRESS', "oskey": True}, None),
    ("wm.call_menu",
     {"type": 'H', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_hook'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_connected'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_curve_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_curve_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Frames",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("screen.frame_offset",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("screen.frame_offset",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("screen.frame_jump",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("end", True),
       ],
      },
     ),
    ("screen.frame_jump",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("end", False),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'UP_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("next", True),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("next", False),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'MEDIA_LAST', "value": 'PRESS'},
     {"properties":
      [("next", True),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'MEDIA_FIRST', "value": 'PRESS'},
     {"properties":
      [("next", False),
       ],
      },
     ),
    ("screen.frame_offset",
     {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("screen.frame_offset",
     {"type": 'WHEELUPMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("screen.animation_play",
     {"type": 'SPACE', "value": 'PRESS', "shift": True},
     {    "active":False,
      },
     ),
    ("screen.animation_play",
     {"type": 'SPACE', "value": 'PRESS', "shift": True, "oskey": True},
     {"properties":
      [("reverse", True),
       ],
      },
     ),
    ("screen.animation_play",
     {"type": 'SPACE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("reverse", True),
       ],
      },
     ),
    ("screen.animation_cancel", {"type": 'ESC', "value": 'PRESS'}, None),
    ("screen.animation_play", {"type": 'MEDIA_PLAY', "value": 'PRESS'}, None),
    ("screen.animation_cancel", {"type": 'MEDIA_STOP', "value": 'PRESS'}, None),
    ],
   },
  ),
 ("Grease Pencil Stroke Edit Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("gpencil.interpolate", {"type": 'E', "value": 'PRESS', "oskey": True}, None),
    ("gpencil.interpolate", {"type": 'E', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.interpolate_sequence", {"type": 'E', "value": 'PRESS', "shift": True, "oskey": True}, None),
    ("gpencil.interpolate_sequence", {"type": 'E', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("gpencil.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'I', "value": 'PRESS', "oskey": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("gpencil.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("gpencil.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("gpencil.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "oskey": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True, "oskey": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "alt": True, "oskey": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True, "alt": True, "oskey": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend", True),
       ("toggle", True),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("entire_strokes", True),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ("entire_strokes", True),
       ],
      },
     ),
    ("gpencil.select_linked", {"type": 'L', "value": 'PRESS'}, None),
    ("gpencil.select_linked", {"type": 'L', "value": 'PRESS', "oskey": True}, None),
    ("gpencil.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.select_alternate", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("gpencil.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("gpencil.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "oskey": True, "repeat": True}, None),
    ("gpencil.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("gpencil.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "oskey": True, "repeat": True}, None),
    ("gpencil.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("gpencil.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("gpencil.extrude_move", {"type": 'E', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_gpencil_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_gpencil_delete'),
       ],
      },
     ),
    ("gpencil.dissolve", {"type": 'X', "value": 'PRESS', "oskey": True}, None),
    ("gpencil.dissolve", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.dissolve", {"type": 'DEL', "value": 'PRESS', "oskey": True}, None),
    ("gpencil.dissolve", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.blank_frame_add", {"type": 'I', "value": 'PRESS', "shift": True}, None),
    ("gpencil.active_frames_delete_all", {"type": 'X', "value": 'PRESS', "shift": True}, None),
    ("gpencil.active_frames_delete_all", {"type": 'DEL', "value": 'PRESS', "shift": True}, None),
    ("gpencil.stroke_separate", {"type": 'P', "value": 'PRESS'}, None),
    ("gpencil.stroke_split", {"type": 'V', "value": 'PRESS'}, None),
    ("gpencil.stroke_join", {"type": 'J', "value": 'PRESS', "oskey": True}, None),
    ("gpencil.stroke_join", {"type": 'J', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.stroke_join",
     {"type": 'J', "value": 'PRESS', "shift": True, "oskey": True},
     {"properties":
      [("type", 'JOINCOPY'),
       ],
      },
     ),
    ("gpencil.stroke_join",
     {"type": 'J', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'JOINCOPY'),
       ],
      },
     ),
    ("gpencil.stroke_cyclical_set",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("type", 'CLOSE'),
       ("geometry", True),
       ],
      },
     ),
    ("gpencil.copy", {"type": 'C', "value": 'PRESS', "oskey": True}, None),
    ("gpencil.copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.paste", {"type": 'V', "value": 'PRESS', "oskey": True}, None),
    ("gpencil.paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'GPENCIL_MT_snap_pie'),
       ],
      },
     ),
    ("gpencil.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("gpencil.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("gpencil.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("gpencil.selection_opacity_toggle", {"type": 'H', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_edit_lines'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_multiedit_line_only'),
       ],
      },
     ),
    ("gpencil.layer_isolate", {"type": 'NUMPAD_ASTERIX', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("name", 'GPENCIL_MT_move_to_layer'),
       ],
      },
     ),
    ("gpencil.layer_merge", {"type": 'M', "value": 'PRESS', "shift": True, "oskey": True}, None),
    ("gpencil.layer_merge", {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("transform.translate", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'}, None),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("transform.tosphere", {"type": 'S', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "alt": True, "oskey": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("transform.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("transform.bend", {"type": 'W', "value": 'PRESS', "shift": True}, None),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'GPENCIL_SHRINKFATTEN'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'GPENCIL_OPACITY'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_connected'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'U', "value": 'PRESS'},
     {"properties":
      [("data_path", 'gpencil_data.use_curve_edit'),
       ],
      },
     ),
    ("object.gpencil_add", {"type": 'A', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "oskey": True},
     {"properties":
      [("name", 'GPENCIL_MT_gpencil_vertex_group'),
       ],
      },
     ),
    ("gpencil.selectmode_toggle",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("mode", 0),
       ],
      },
     ),
    ("gpencil.selectmode_toggle",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("mode", 1),
       ],
      },
     ),
    ("gpencil.selectmode_toggle",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("mode", 2),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'Y', "value": 'PRESS'},
     {"properties":
      [("name", 'GPENCIL_MT_layer_active'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'I', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_gpencil_animation'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_gpencil_edit_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_gpencil_edit_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Grease Pencil Stroke Paint (Tint)",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("gpencil.vertex_paint",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("wait_for_input", False),
       ],
      },
     ),
    ("gpencil.vertex_paint",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "oskey": True},
     {"properties":
      [("wait_for_input", False),
       ],
      },
     ),
    ],
   },
  ),
 ("Grease Pencil Stroke Vertex (Draw)",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("gpencil.vertex_paint",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("wait_for_input", False),
       ],
      },
     ),
    ("gpencil.vertex_paint",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "oskey": True},
     {"properties":
      [("wait_for_input", False),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_vertex_paint.brush.gpencil_settings.pen_strength'),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_vertex_paint.brush.size'),
       ],
      },
     ),
    ],
   },
  ),
 ("Mask Editing",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("mask.new", {"type": 'N', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'MASK_MT_add'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit_mask'),
       ],
      },
     ),
    ("mask.add_vertex_slide", {"type": 'LEFTMOUSE', "value": 'PRESS', "oskey": True}, None),
    ("mask.add_feather_vertex_slide", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "oskey": True}, None),
    ("mask.delete", {"type": 'X', "value": 'PRESS'}, None),
    ("mask.delete", {"type": 'DEL', "value": 'PRESS'}, None),
    ("mask.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("mask.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("mask.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("mask.select_all",
     {"type": 'I', "value": 'PRESS', "oskey": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("mask.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("mask.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("mask.select_linked", {"type": 'L', "value": 'PRESS', "oskey": True}, None),
    ("mask.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("mask.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("mask.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("mask.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("mask.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("mask.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "alt": True, "oskey": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("mask.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("mask.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True, "alt": True, "oskey": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("mask.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("mask.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "oskey": True, "repeat": True}, None),
    ("mask.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("mask.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "oskey": True, "repeat": True}, None),
    ("mask.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("mask.hide_view_clear", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("mask.hide_view_set",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("mask.hide_view_set",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("clip.select", {"type": 'LEFTMOUSE', "value": 'PRESS', "oskey": True}, None),
    ("clip.select", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("mask.cyclic_toggle", {"type": 'C', "value": 'PRESS', "alt": True}, None),
    ("mask.slide_point", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("mask.slide_spline_curvature", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("mask.handle_type_set", {"type": 'V', "value": 'PRESS'}, None),
    ("mask.normals_make_consistent", {"type": 'N', "value": 'PRESS', "shift": True}, None),
    ("mask.parent_set", {"type": 'P', "value": 'PRESS', "oskey": True}, None),
    ("mask.parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("mask.parent_clear", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("mask.shape_key_insert", {"type": 'I', "value": 'PRESS'}, None),
    ("mask.shape_key_clear", {"type": 'I', "value": 'PRESS', "alt": True}, None),
    ("mask.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("mask.copy_splines", {"type": 'C', "value": 'PRESS', "oskey": True}, None),
    ("mask.copy_splines", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("mask.paste_splines", {"type": 'V', "value": 'PRESS', "oskey": True}, None),
    ("mask.paste_splines", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.translate", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'}, None),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("transform.tosphere", {"type": 'S', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "alt": True, "oskey": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'MASK_SHRINKFATTEN'),
       ],
      },
     ),
    ("uv.cursor_set", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("transform.translate",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True},
     {"properties":
      [("cursor_transform", True),
       ("release_confirm", True),
       ],
      },
     ),
    ],
   },
  ),
 ("Mesh",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu",
     {"type": 'C', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'MESH_MT_CopyFaceSettings'),
       ],
      },
     ),
    ("mesh.loopcut_slide",
     {"type": 'R', "value": 'PRESS', "oskey": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.loopcut_slide",
     {"type": 'R', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.offset_edge_loops_slide",
     {"type": 'R', "value": 'PRESS', "shift": True, "oskey": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.offset_edge_loops_slide",
     {"type": 'R', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.inset", {"type": 'I', "value": 'PRESS'}, None),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "oskey": True},
     {"properties":
      [("affect", 'EDGES'),
       ],
      },
     ),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("affect", 'EDGES'),
       ],
      },
     ),
    ("transform.shrink_fatten", {"type": 'S', "value": 'PRESS', "alt": True}, None),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "shift": True, "oskey": True},
     {"properties":
      [("affect", 'VERTICES'),
       ],
      },
     ),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("affect", 'VERTICES'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "oskey": True},
     {"properties":
      [("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "oskey": True},
     {"properties":
      [("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "oskey": True},
     {"properties":
      [("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "oskey": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "shift": True, "oskey": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "shift": True, "oskey": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.loop_select", {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True}, None),
    ("mesh.loop_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("mesh.edgering_select", {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True, "oskey": True}, None),
    ("mesh.edgering_select", {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True, "alt": True}, None),
    ("mesh.edgering_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True, "oskey": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("mesh.edgering_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "oskey": True},
     {"properties":
      [("use_fill", False),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("use_fill", False),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "oskey": True},
     {"properties":
      [("use_fill", True),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("use_fill", True),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'I', "value": 'PRESS', "oskey": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("mesh.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "oskey": True, "repeat": True}, None),
    ("mesh.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("mesh.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "oskey": True, "repeat": True}, None),
    ("mesh.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("mesh.select_next_item", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "oskey": True, "repeat": True}, None),
    ("mesh.select_next_item", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True}, None),
    ("mesh.select_prev_item", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "oskey": True, "repeat": True}, None),
    ("mesh.select_prev_item", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True}, None),
    ("mesh.select_linked", {"type": 'L', "value": 'PRESS', "oskey": True}, None),
    ("mesh.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("mesh.select_mirror", {"type": 'M', "value": 'PRESS', "shift": True, "oskey": True}, None),
    ("mesh.select_mirror", {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_select_similar'),
       ],
      },
     ),
    ("mesh.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True},
     {"properties":
      [("inside", False),
       ],
      },
     ),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True, "oskey": True},
     {"properties":
      [("inside", True),
       ],
      },
     ),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("inside", True),
       ],
      },
     ),
    ("view3d.edit_mesh_extrude_move_normal", {"type": 'E', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_extrude'),
       ],
      },
     ),
    ("transform.edge_crease", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("mesh.fill", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "oskey": True},
     {"properties":
      [("quad_method", 'BEAUTY'),
       ("ngon_method", 'BEAUTY'),
       ],
      },
     ),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("quad_method", 'BEAUTY'),
       ("ngon_method", 'BEAUTY'),
       ],
      },
     ),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "shift": True, "oskey": True},
     {"properties":
      [("quad_method", 'FIXED'),
       ("ngon_method", 'CLIP'),
       ],
      },
     ),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("quad_method", 'FIXED'),
       ("ngon_method", 'CLIP'),
       ],
      },
     ),
    ("mesh.tris_convert_to_quads", {"type": 'J', "value": 'PRESS', "alt": True}, None),
    ("mesh.rip_move",
     {"type": 'V', "value": 'PRESS'},
     {"properties":
      [("MESH_OT_rip",
        [("use_fill", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.rip_move",
     {"type": 'V', "value": 'PRESS', "alt": True},
     {"properties":
      [("MESH_OT_rip",
        [("use_fill", True),
         ],
        ),
       ],
      },
     ),
    ("mesh.rip_edge_move", {"type": 'D', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_merge'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_split'),
       ],
      },
     ),
    ("mesh.edge_face_add", {"type": 'F', "value": 'PRESS', "repeat": True}, None),
    ("mesh.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_mesh_add'),
       ],
      },
     ),
    ("mesh.separate", {"type": 'P', "value": 'PRESS'}, None),
    ("mesh.split", {"type": 'Y', "value": 'PRESS'}, None),
    ("mesh.vert_connect_path", {"type": 'J', "value": 'PRESS'}, None),
    ("mesh.point_normals", {"type": 'L', "value": 'PRESS', "alt": True}, None),
    ("transform.vert_slide", {"type": 'V', "value": 'PRESS', "shift": True}, None),
    ("mesh.dupli_extrude_cursor",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "oskey": True},
     {"properties":
      [("rotate_source", True),
       ],
      },
     ),
    ("mesh.dupli_extrude_cursor",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("rotate_source", True),
       ],
      },
     ),
    ("mesh.dupli_extrude_cursor",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "shift": True, "oskey": True},
     {"properties":
      [("rotate_source", False),
       ],
      },
     ),
    ("mesh.dupli_extrude_cursor",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("rotate_source", False),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("mesh.dissolve_mode", {"type": 'X', "value": 'PRESS', "oskey": True}, None),
    ("mesh.dissolve_mode", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.dissolve_mode", {"type": 'DEL', "value": 'PRESS', "oskey": True}, None),
    ("mesh.dissolve_mode", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.knife_tool",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("use_occlude_geometry", True),
       ("only_selected", False),
       ],
      },
     ),
    ("mesh.knife_tool",
     {"type": 'K', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_occlude_geometry", False),
       ("only_selected", True),
       ],
      },
     ),
    ("object.vertex_parent_set", {"type": 'P', "value": 'PRESS', "oskey": True}, None),
    ("wm.call_menu",
     {"type": 'F', "value": 'PRESS', "oskey": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_faces'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "oskey": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_edges'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'V', "value": 'PRESS', "oskey": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_vertices'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'H', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_hook'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'U', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_uv_map'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "oskey": True},
     {"properties":
      [("name", 'VIEW3D_MT_vertex_group'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'N', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_normals'),
       ],
      },
     ),
    ("object.vertex_group_remove_from", {"type": 'G', "value": 'PRESS', "alt": True, "oskey": True}, None),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_connected'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_context_menu'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'V', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'E', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'F', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'FACE'),
       ],
      },
     ),
    ],
   },
  ),
 ("NLA Editor",
  {"space_type": 'NLA_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("nla.click_select",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("nla.click_select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("nla.select_leftright",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "oskey": True},
     {"properties":
      [("mode", 'CHECK'),
       ],
      },
     ),
    ("nla.select_leftright",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("mode", 'CHECK'),
       ],
      },
     ),
    ("nla.select_leftright",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "oskey": True},
     {"properties":
      [("mode", 'CHECK'),
       ("extend", True),
       ],
      },
     ),
    ("nla.select_leftright",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'CHECK'),
       ("extend", True),
       ],
      },
     ),
    ("nla.select_leftright",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("mode", 'LEFT'),
       ],
      },
     ),
    ("nla.select_leftright",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("mode", 'RIGHT'),
       ],
      },
     ),
    ("nla.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("nla.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("nla.select_all",
     {"type": 'I', "value": 'PRESS', "oskey": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("nla.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("nla.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("nla.select_box",
     {"type": 'B', "value": 'PRESS'},
     {"properties":
      [("axis_range", False),
       ],
      },
     ),
    ("nla.select_box",
     {"type": 'B', "value": 'PRESS', "alt": True},
     {"properties":
      [("axis_range", True),
       ],
      },
     ),
    ("nla.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("tweak", True),
       ("mode", 'SET'),
       ],
      },
     ),
    ("nla.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "shift": True},
     {"properties":
      [("tweak", True),
       ("mode", 'ADD'),
       ],
      },
     ),
    ("nla.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "oskey": True},
     {"properties":
      [("tweak", True),
       ("mode", 'SUB'),
       ],
      },
     ),
    ("nla.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("tweak", True),
       ("mode", 'SUB'),
       ],
      },
     ),
    ("nla.previewrange_set", {"type": 'P', "value": 'PRESS', "alt": True, "oskey": True}, None),
    ("nla.previewrange_set", {"type": 'P', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("nla.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("nla.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("nla.view_selected", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("nla.view_frame", {"type": 'NUMPAD_0', "value": 'PRESS'}, None),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'NLA_MT_view_pie'),
       ],
      },
     ),
    ("nla.actionclip_add", {"type": 'A', "value": 'PRESS', "shift": True}, None),
    ("nla.transition_add", {"type": 'T', "value": 'PRESS', "shift": True}, None),
    ("nla.soundclip_add", {"type": 'K', "value": 'PRESS', "shift": True}, None),
    ("nla.meta_add", {"type": 'G', "value": 'PRESS', "oskey": True}, None),
    ("nla.meta_add", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("nla.meta_remove", {"type": 'G', "value": 'PRESS', "alt": True, "oskey": True}, None),
    ("nla.meta_remove", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("nla.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("nla.duplicate_linked_move", {"type": 'D', "value": 'PRESS', "alt": True}, None),
    ("nla.make_single_user", {"type": 'U', "value": 'PRESS'}, None),
    ("nla.delete", {"type": 'X', "value": 'PRESS'}, None),
    ("nla.delete", {"type": 'DEL', "value": 'PRESS'}, None),
    ("nla.split", {"type": 'Y', "value": 'PRESS'}, None),
    ("nla.mute_toggle", {"type": 'H', "value": 'PRESS'}, None),
    ("nla.swap", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("nla.move_up", {"type": 'PAGE_UP', "value": 'PRESS', "repeat": True}, None),
    ("nla.move_down", {"type": 'PAGE_DOWN', "value": 'PRESS', "repeat": True}, None),
    ("nla.apply_scale", {"type": 'A', "value": 'PRESS', "oskey": True}, None),
    ("nla.clear_scale", {"type": 'S', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'NLA_MT_snap_pie'),
       ],
      },
     ),
    ("nla.fmodifier_add", {"type": 'M', "value": 'PRESS', "shift": True, "oskey": True}, None),
    ("nla.fmodifier_add", {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("transform.transform",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("mode", 'TRANSLATION'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("mode", 'TRANSLATION'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("mode", 'TIME_EXTEND'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS'},
     {"properties":
      [("mode", 'TIME_SCALE'),
       ],
      },
     ),
    ("marker.add", {"type": 'M', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'NLA_MT_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'NLA_MT_context_menu'),
       ],
      },
     ),
    ("anim.change_frame", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True}, None),
    ],
   },
  ),
 ("Object Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu",
     {"type": 'C', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_copypopup'),
       ],
      },
     ),
    ("object.booltool_auto_slice", {"type": 'NUMPAD_SLASH', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("object.booltool_auto_intersect", {"type": 'NUMPAD_ASTERIX', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("object.booltool_auto_difference", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("object.booltool_auto_union", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("btool.to_mesh", {"type": 'NUMPAD_ENTER', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("btool.brush_to_mesh", {"type": 'NUMPAD_ENTER', "value": 'PRESS', "ctrl": True}, None),
    ("btool.boolean_slice", {"type": 'NUMPAD_SLASH', "value": 'PRESS'}, None),
    ("btool.boolean_inters", {"type": 'NUMPAD_ASTERIX', "value": 'PRESS'}, None),
    ("btool.boolean_diff", {"type": 'NUMPAD_MINUS', "value": 'PRESS'}, None),
    ("btool.boolean_union", {"type": 'NUMPAD_PLUS', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'B', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_booltool_menu'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit_objects'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'I', "value": 'PRESS', "oskey": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("object.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "oskey": True, "repeat": True}, None),
    ("object.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("object.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "oskey": True, "repeat": True}, None),
    ("object.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("object.select_linked", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("object.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("object.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", False),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", True),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", False),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", True),
       ],
      },
     ),
    ("object.parent_set", {"type": 'P', "value": 'PRESS', "oskey": True}, None),
    ("object.parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("object.parent_clear", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("object.location_clear",
     {"type": 'G', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.rotation_clear",
     {"type": 'R', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.scale_clear",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("use_global", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'X', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_global", True),
       ],
      },
     ),
    ("object.delete",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("use_global", False),
       ("confirm", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'DEL', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_global", True),
       ("confirm", False),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_add'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "oskey": True},
     {"properties":
      [("name", 'VIEW3D_MT_object_apply'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'L', "value": 'PRESS', "oskey": True},
     {"properties":
      [("name", 'VIEW3D_MT_make_links'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'L', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_make_links'),
       ],
      },
     ),
    ("object.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("object.duplicate_move_linked", {"type": 'D', "value": 'PRESS', "alt": True}, None),
    ("object.join", {"type": 'J', "value": 'PRESS', "oskey": True}, None),
    ("object.join", {"type": 'J', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'PERIOD', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'tool_settings.use_transform_data_origin'),
       ],
      },
     ),
    ("anim.keyframe_insert_menu", {"type": 'I', "value": 'PRESS'}, None),
    ("anim.keyframe_delete_v3d", {"type": 'I', "value": 'PRESS', "alt": True}, None),
    ("anim.keying_set_active_set", {"type": 'I', "value": 'PRESS', "shift": True, "alt": True, "oskey": True}, None),
    ("anim.keying_set_active_set", {"type": 'I', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("collection.create", {"type": 'G', "value": 'PRESS', "oskey": True}, None),
    ("collection.create", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("collection.objects_remove", {"type": 'G', "value": 'PRESS', "alt": True, "oskey": True}, None),
    ("collection.objects_remove", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("collection.objects_remove_all", {"type": 'G', "value": 'PRESS', "shift": True, "alt": True, "oskey": True}, None),
    ("collection.objects_remove_all", {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("collection.objects_add_active", {"type": 'G', "value": 'PRESS', "shift": True, "oskey": True}, None),
    ("collection.objects_add_active", {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("collection.objects_remove_active", {"type": 'G', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("object.subdivision_set",
     {"type": 'ZERO', "value": 'PRESS', "oskey": True},
     {"properties":
      [("level", 0),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ZERO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 0),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ONE', "value": 'PRESS', "oskey": True},
     {"properties":
      [("level", 1),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 1),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'TWO', "value": 'PRESS', "oskey": True},
     {"properties":
      [("level", 2),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 2),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'THREE', "value": 'PRESS', "oskey": True},
     {"properties":
      [("level", 3),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 3),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FOUR', "value": 'PRESS', "oskey": True},
     {"properties":
      [("level", 4),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FOUR', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 4),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FIVE', "value": 'PRESS', "oskey": True},
     {"properties":
      [("level", 5),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FIVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 5),
       ("relative", False),
       ],
      },
     ),
    ("object.move_to_collection", {"type": 'M', "value": 'PRESS'}, None),
    ("object.link_to_collection", {"type": 'M', "value": 'PRESS', "shift": True}, None),
    ("object.hide_view_clear", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("object.hide_view_set",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("object.hide_view_set",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("object.hide_collection", {"type": 'H', "value": 'PRESS', "ctrl": True}, None),
    ("object.hide_collection",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("collection_index", 1),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("collection_index", 2),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("collection_index", 3),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FOUR', "value": 'PRESS'},
     {"properties":
      [("collection_index", 4),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FIVE', "value": 'PRESS'},
     {"properties":
      [("collection_index", 5),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SIX', "value": 'PRESS'},
     {"properties":
      [("collection_index", 6),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SEVEN', "value": 'PRESS'},
     {"properties":
      [("collection_index", 7),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'EIGHT', "value": 'PRESS'},
     {"properties":
      [("collection_index", 8),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'NINE', "value": 'PRESS'},
     {"properties":
      [("collection_index", 9),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ZERO', "value": 'PRESS'},
     {"properties":
      [("collection_index", 10),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ONE', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 11),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'TWO', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 12),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'THREE', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 13),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FOUR', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 14),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FIVE', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 15),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SIX', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 16),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SEVEN', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 17),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'EIGHT', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 18),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'NINE', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 19),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ZERO', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 20),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ONE', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 1),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'TWO', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 2),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'THREE', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 3),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FOUR', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 4),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FIVE', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 5),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SIX', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 6),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SEVEN', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 7),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'EIGHT', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 8),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'NINE', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 9),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ZERO', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 10),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 11),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'TWO', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 12),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'THREE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 13),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FOUR', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 14),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FIVE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 15),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SIX', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 16),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SEVEN', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 17),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'EIGHT', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 18),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'NINE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 19),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ZERO', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 20),
       ("extend", True),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_object_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_object_context_menu'),
       ],
      },
     ),
    ("object.shade_smooth",
     {"type": 'A', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("use_auto_smooth", True),
       ],
      },
     ),
    ],
   },
  ),
 ("Outliner",
  {"space_type": 'OUTLINER', "region_type": 'WINDOW'},
  {"items":
   [("outliner.highlight_update", {"type": 'MOUSEMOVE', "value": 'ANY', "any": True}, None),
    ("outliner.item_rename", {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'}, None),
    ("outliner.item_rename",
     {"type": 'RET', "value": 'PRESS'},
     {"properties":
      [("use_active", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "oskey": True},
     {"properties":
      [("extend", True),
       ("deselect_all", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("extend", True),
       ("deselect_all", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend_range", True),
       ("deselect_all", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "oskey": True},
     {"properties":
      [("extend", True),
       ("extend_range", True),
       ("deselect_all", True),
       ],
      },
     ),
    ("outliner.item_activate",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ("extend_range", True),
       ("deselect_all", True),
       ],
      },
     ),
    ("outliner.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("outliner.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("tweak", True),
       ],
      },
     ),
    ("outliner.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "shift": True},
     {"properties":
      [("tweak", True),
       ("mode", 'ADD'),
       ],
      },
     ),
    ("outliner.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "oskey": True},
     {"properties":
      [("tweak", True),
       ("mode", 'SUB'),
       ],
      },
     ),
    ("outliner.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("tweak", True),
       ("mode", 'SUB'),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'UP_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'UP'),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'UP_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'UP'),
       ("extend", True),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'DOWN'),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'DOWN'),
       ("extend", True),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'LEFT'),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'LEFT'),
       ("toggle_all", True),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'RIGHT'),
       ],
      },
     ),
    ("outliner.select_walk",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'RIGHT'),
       ("toggle_all", True),
       ],
      },
     ),
    ("outliner.item_openclose",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("all", False),
       ],
      },
     ),
    ("outliner.item_openclose",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("all", True),
       ],
      },
     ),
    ("outliner.item_openclose",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("all", False),
       ],
      },
     ),
    ("outliner.operation", {"type": 'RIGHTMOUSE', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'OUTLINER_MT_context_menu'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'OUTLINER_MT_view_pie'),
       ],
      },
     ),
    ("outliner.item_drag_drop", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'}, None),
    ("outliner.item_drag_drop", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "shift": True}, None),
    ("outliner.show_hierarchy", {"type": 'HOME', "value": 'PRESS'}, None),
    ("outliner.show_active", {"type": 'PERIOD', "value": 'PRESS'}, None),
    ("outliner.show_active", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("outliner.scroll_page",
     {"type": 'PAGE_DOWN', "value": 'PRESS', "repeat": True},
     {"properties":
      [("up", False),
       ],
      },
     ),
    ("outliner.scroll_page",
     {"type": 'PAGE_UP', "value": 'PRESS', "repeat": True},
     {"properties":
      [("up", True),
       ],
      },
     ),
    ("outliner.show_one_level", {"type": 'NUMPAD_PLUS', "value": 'PRESS'}, None),
    ("outliner.show_one_level",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS'},
     {"properties":
      [("open", False),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'I', "value": 'PRESS', "oskey": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("outliner.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("outliner.expanded_toggle", {"type": 'A', "value": 'PRESS', "shift": True}, None),
    ("outliner.keyingset_add_selected", {"type": 'K', "value": 'PRESS'}, None),
    ("outliner.keyingset_remove_selected", {"type": 'K', "value": 'PRESS', "alt": True}, None),
    ("anim.keyframe_insert", {"type": 'I', "value": 'PRESS'}, None),
    ("anim.keyframe_delete", {"type": 'I', "value": 'PRESS', "alt": True}, None),
    ("outliner.drivers_add_selected", {"type": 'D', "value": 'PRESS', "oskey": True}, None),
    ("outliner.drivers_add_selected", {"type": 'D', "value": 'PRESS', "ctrl": True}, None),
    ("outliner.drivers_delete_selected", {"type": 'D', "value": 'PRESS', "alt": True, "oskey": True}, None),
    ("outliner.drivers_delete_selected", {"type": 'D', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("outliner.collection_new", {"type": 'C', "value": 'PRESS'}, None),
    ("outliner.delete", {"type": 'X', "value": 'PRESS'}, None),
    ("outliner.delete", {"type": 'DEL', "value": 'PRESS'}, None),
    ("object.move_to_collection", {"type": 'M', "value": 'PRESS'}, None),
    ("object.link_to_collection", {"type": 'M', "value": 'PRESS', "shift": True}, None),
    ("outliner.collection_exclude_set", {"type": 'E', "value": 'PRESS'}, None),
    ("outliner.collection_exclude_clear", {"type": 'E', "value": 'PRESS', "alt": True}, None),
    ("outliner.hide", {"type": 'H', "value": 'PRESS'}, None),
    ("outliner.unhide_all", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("outliner.id_copy", {"type": 'C', "value": 'PRESS', "oskey": True}, None),
    ("outliner.id_copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("outliner.id_paste", {"type": 'V', "value": 'PRESS', "oskey": True}, None),
    ("outliner.id_paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ],
   },
  ),
 ("Property Editor",
  {"space_type": 'PROPERTIES', "region_type": 'WINDOW'},
  {"items":
   [("buttons.context_menu", {"type": 'RIGHTMOUSE', "value": 'PRESS'}, None),
    ("screen.space_context_cycle",
     {"type": 'WHEELUPMOUSE', "value": 'PRESS', "oskey": True},
     {"properties":
      [("direction", 'PREV'),
       ],
      },
     ),
    ("screen.space_context_cycle",
     {"type": 'WHEELUPMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("direction", 'PREV'),
       ],
      },
     ),
    ("screen.space_context_cycle",
     {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "oskey": True},
     {"properties":
      [("direction", 'NEXT'),
       ],
      },
     ),
    ("screen.space_context_cycle",
     {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("direction", 'NEXT'),
       ],
      },
     ),
    ("buttons.start_filter", {"type": 'F', "value": 'PRESS', "oskey": True}, None),
    ("buttons.start_filter", {"type": 'F', "value": 'PRESS', "ctrl": True}, None),
    ("buttons.clear_filter", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("object.modifier_set_active", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("object.modifier_remove",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("report", True),
       ],
      },
     ),
    ("object.modifier_remove",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("report", True),
       ],
      },
     ),
    ("object.modifier_copy", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("object.modifier_apply",
     {"type": 'A', "value": 'PRESS', "oskey": True},
     {"properties":
      [("report", True),
       ],
      },
     ),
    ("object.gpencil_modifier_remove",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("report", True),
       ],
      },
     ),
    ("object.gpencil_modifier_remove",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("report", True),
       ],
      },
     ),
    ("object.gpencil_modifier_copy", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("object.gpencil_modifier_apply",
     {"type": 'A', "value": 'PRESS', "oskey": True},
     {"properties":
      [("report", True),
       ],
      },
     ),
    ("object.shaderfx_remove",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("report", True),
       ],
      },
     ),
    ("object.shaderfx_remove",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("report", True),
       ],
      },
     ),
    ("object.shaderfx_copy", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("constraint.delete",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("report", True),
       ],
      },
     ),
    ("constraint.delete",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("report", True),
       ],
      },
     ),
    ("constraint.copy", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("constraint.apply",
     {"type": 'A', "value": 'PRESS', "oskey": True},
     {"properties":
      [("report", True),
       ],
      },
     ),
    ],
   },
  ),
 ("Screen",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("screen.animation_step", {"type": 'TIMER0', "value": 'ANY', "any": True}, None),
    ("screen.region_blend", {"type": 'TIMERREGION', "value": 'ANY', "any": True}, None),
    ("screen.space_context_cycle",
     {"type": 'TAB', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("direction", 'NEXT'),
       ],
      },
     ),
    ("screen.space_context_cycle",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "oskey": True},
     {"properties":
      [("direction", 'PREV'),
       ],
      },
     ),
    ("screen.space_context_cycle",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("direction", 'PREV'),
       ],
      },
     ),
    ("screen.workspace_cycle",
     {"type": 'PAGE_DOWN', "value": 'PRESS', "oskey": True},
     {"properties":
      [("direction", 'NEXT'),
       ],
      },
     ),
    ("screen.workspace_cycle",
     {"type": 'PAGE_DOWN', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("direction", 'NEXT'),
       ],
      },
     ),
    ("screen.workspace_cycle",
     {"type": 'PAGE_UP', "value": 'PRESS', "oskey": True},
     {"properties":
      [("direction", 'PREV'),
       ],
      },
     ),
    ("screen.workspace_cycle",
     {"type": 'PAGE_UP', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("direction", 'PREV'),
       ],
      },
     ),
    ("screen.region_quadview", {"type": 'Q', "value": 'PRESS'}, None),
    ("screen.repeat_last", {"type": 'R', "value": 'PRESS', "shift": True, "repeat": True}, None),
    ("file.execute", {"type": 'RET', "value": 'PRESS'}, None),
    ("file.execute", {"type": 'NUMPAD_ENTER', "value": 'PRESS'}, None),
    ("file.cancel", {"type": 'ESC', "value": 'PRESS'}, None),
    ("asset.catalog_undo", {"type": 'Z', "value": 'PRESS', "oskey": True, "repeat": True}, None),
    ("asset.catalog_redo", {"type": 'Z', "value": 'PRESS', "shift": True, "oskey": True, "repeat": True}, None),
    ("ed.undo", {"type": 'Z', "value": 'PRESS', "oskey": True, "repeat": True}, None),
    ("ed.redo", {"type": 'Z', "value": 'PRESS', "shift": True, "oskey": True, "repeat": True}, None),
    ("render.render",
     {"type": 'F12', "value": 'PRESS'},
     {"properties":
      [("use_viewport", True),
       ],
      },
     ),
    ("render.render",
     {"type": 'F12', "value": 'PRESS', "oskey": True},
     {"properties":
      [("animation", True),
       ("use_viewport", True),
       ],
      },
     ),
    ("render.render",
     {"type": 'F12', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("animation", True),
       ("use_viewport", True),
       ],
      },
     ),
    ("render.view_cancel", {"type": 'ESC', "value": 'PRESS'}, None),
    ("render.view_show", {"type": 'F11', "value": 'PRESS'}, None),
    ("render.play_rendered_anim", {"type": 'F11', "value": 'PRESS', "oskey": True}, None),
    ("render.play_rendered_anim", {"type": 'F11', "value": 'PRESS', "ctrl": True}, None),
    ("screen.screen_full_area", {"type": 'SPACE', "value": 'PRESS', "ctrl": True}, None),
    ("screen.screen_full_area",
     {"type": 'SPACE', "value": 'PRESS', "alt": True, "oskey": True},
     {"properties":
      [("use_hide_panels", True),
       ],
      },
     ),
    ("screen.screen_full_area",
     {"type": 'SPACE', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_hide_panels", True),
       ],
      },
     ),
    ("screen.redo_last", {"type": 'U', "value": 'PRESS'}, None),
    ("screen.userpref_show", {"type": 'COMMA', "value": 'PRESS', "oskey": True}, None),
    ("none", {"type": 'A', "value": 'PRESS'}, None),
    ],
   },
  ),
 ("Window",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu",
     {"type": 'N', "value": 'PRESS', "oskey": True},
     {"properties":
      [("name", 'TOPBAR_MT_file_new'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'O', "value": 'PRESS', "shift": True, "oskey": True},
     {"properties":
      [("name", 'TOPBAR_MT_file_open_recent'),
       ],
      },
     ),
    ("wm.open_mainfile", {"type": 'O', "value": 'PRESS', "oskey": True}, None),
    ("wm.save_mainfile", {"type": 'S', "value": 'PRESS', "oskey": True}, None),
    ("wm.save_as_mainfile", {"type": 'S', "value": 'PRESS', "shift": True, "oskey": True}, None),
    ("wm.quit_blender", {"type": 'Q', "value": 'PRESS', "oskey": True}, None),
    ("wm.call_menu",
     {"type": 'Q', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'SCREEN_MT_user_menu'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F1', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'FILE_BROWSER'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F2', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'CLIP_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F3', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'NODE_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F4', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'CONSOLE'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F5', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'VIEW_3D'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F6', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'GRAPH_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F7', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'PROPERTIES'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F8', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'SEQUENCE_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F9', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'OUTLINER'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F10', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'IMAGE_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F11', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'TEXT_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F12', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'DOPESHEET_EDITOR'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'NDOF_BUTTON_MENU', "value": 'PRESS'},
     {"properties":
      [("name", 'USERPREF_PT_ndof_settings'),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_PLUS', "value": 'PRESS'},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 1.1),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_MINUS', "value": 'PRESS'},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 0.90909094),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_PLUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 1.5),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_MINUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 0.6666667),
       ],
      },
     ),
    ("info.reports_display_update", {"type": 'TIMER_REPORT', "value": 'ANY', "any": True}, None),
    ("wm.doc_view_manual_ui_context", {"type": 'F1', "value": 'PRESS'}, None),
    ("wm.call_panel",
     {"type": 'F2', "value": 'PRESS'},
     {"properties":
      [("name", 'TOPBAR_PT_name'),
       ("keep_open", False),
       ],
      },
     ),
    ("wm.batch_rename", {"type": 'F2', "value": 'PRESS', "oskey": True}, None),
    ("wm.batch_rename", {"type": 'F2', "value": 'PRESS', "ctrl": True}, None),
    ("wm.search_menu", {"type": 'F3', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'F4', "value": 'PRESS'},
     {"properties":
      [("name", 'TOPBAR_MT_file_context_menu'),
       ],
      },
     ),
    ("wm.toolbar_fallback_pie", {"type": 'W', "value": 'PRESS', "alt": True}, None),
    ("wm.search_menu", {"type": 'SPACE', "value": 'PRESS'}, None),
    ("wm.context_toggle",
     {"type": 'C', "value": 'PRESS', "repeat": True},
     {"properties":
      [("data_path", 'space_data.shading.show_cavity'),
       ],
      },
     ),
    ],
   },
  ),
 ]


if __name__ == "__main__":
    # Only add keywords that are supported.
    from bpy.app import version as blender_version
    keywords = {}
    if blender_version >= (2, 92, 0):
        keywords["keyconfig_version"] = keyconfig_version
    import os
    from bl_keymap_utils.io import keyconfig_import_from_data
    keyconfig_import_from_data(
        os.path.splitext(os.path.basename(__file__))[0],
        keyconfig_data,
        **keywords,
    )
